spring:
  application:
    name: eureka-feign-client-consumer

server:
  port: 8074

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${random.value}
    
    