spring:
   cloud:
      config:
         server:
            git:
               uri: https://github.com/RameshSv/exp-work/tree/Oct2018/eureka-cloud-config-server/src/main/resources/common-config
server:
   port: 8888
   
